---
name: Check Go Modules Licenses
on:
  push:

jobs:
  check-license:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/go-check-license.yaml@8d542a426ce561c7dce745f6b9cee068d1d7e101 # v2.0.10
